### ISSUE TITLE
Remove Quarkus GitHub Bot literals

### ISSUE THREAD

**Issue by The-Huginn** [quarkusio/build-reporter#180]
Hi,

would it be possible to remove literals connected to Quarkus GitHub Bot? We would like to reuse this library and I see hard-coded values connected to Quarkus GitHub Bot. It's not a deal breaker obviously, but I think it might be nice to replace some constants such as 
`public static final String MESSAGE_ID_ACTIVE = "<!-- Quarkus-GitHub-Bot/msg-id:workflow-run-status-active -->"`
with
`public static final String MESSAGE_ID_ACTIVE = "<!-- Build-Reporter/msg-id:workflow-run-status-active -->"` in `WorkflowConstants.java`.

**Comment by gsmet** [comment]
Ah yes, you're right. It's historical as this library was actually extracted from the Quarkus GitHub Bot to also be made usable in an action.
We can adjust the constants but we will need to keep the old ones for a while and support them as we don't want to break the Quarkus flow.

**Comment by The-Huginn** [comment]
Thanks for that. I was researching CI Actions for building the report and that's amazing work guys, the magic :exploding_head: 
I can try to move the outdated constants to deprecated versions and compare for new and deprecated string literals in code. If you agree obviously

**Comment by gsmet** [comment]
Yes, that would be awesome.

The idea is to:
- have deprecated constants for the old strings and only use them for lookups (as a backup)
- move everything else to the new strings

**Comment by gsmet** [comment]
@The-Huginn btw, I added a bit more doc to the README. And also pointed to https://github.com/quarkusio/action-build-reporter/ which might be useful too.

Don't hesitate to ping me, we can organize a call to discuss your options and how to best use this.

**Comment by The-Huginn** [comment]
I have implemented something. I will have to leave now for a bit. But if I got the idea wrong, we can for sure have a call later on today or tomorrow. Thanks for the option :relaxed:

**Comment by gsmet** [comment]
@The-Huginn 3.7.0 is on its way to Maven Central with your changes.

As for the discussion, I was more thinking of a global discussion about how you can use it in WildFly and all it can offer you (and probably some pointers on how to set everything up).

You know where to find me :).

**Comment by The-Huginn** [comment]
Absolutely, I will keep that in mind and tell also my peer :blush: . Thanks for quick help today :+1:

**Comment by The-Huginn** [comment]
Just a quick update, I have tried to deploy it on my test PR and it minimized the old comment and put in a new one with updated literals. Hopefully, it will be working well

**Comment by gsmet** [comment]
Yeah I also tested before merging.
I think we are all good.
